routes/web.php
<?php
Route::match(['get', 'post'], '/login', 'Admin\AuthController@login')->name('login');
Route::match(['get', 'post'], '/register', 'Admin\AuthController@register')->name('register');

Route::group(['prefix' => 'admin', 'middleware' => 'roles', 'roles' => ['Admin', 'Author', 'User']], function () {
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::get('settings', 'Admin\SettingsController@settings')->name('admin.settings');
    Route::post('settings-post', 'Admin\SettingsController@postChangePassword')->name('admin.settings.post');

    Route::get('blog/category/{slug?}', 'User\CategoryController@category')->name('category');
    Route::get('blog/article/{slug?}', 'User\ArticleController@article')->name('article');

    Route::get('blog/search', 'User\SearchController@search')->name('admin.search');
});

Route::group(['prefix' => 'admin', 'middleware' => 'roles', 'roles' => ['Admin', 'Author']], function () {
    Route::resource('category', 'Admin\CategoryController', ['as' => 'admin']);
    Route::resource('article', 'Admin\ArticleController', ['as' => 'admin']);
});

Route::group(['prefix' => 'admin', 'middleware' => 'roles', 'roles' => ['Admin']], function () {
    Route::resource('user', 'Admin\UserController', ['as' => 'admin']);

    Route::post('users/update-roles', 'Admin\UserController@postAdminAssignRoles')->name('admin.assign');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('logout', 'Admin\AuthController@logout')->name('logout');
    Route::get('/', function () {
        return view('welcome');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function roles()
    {
        return $this->belongsToMany('App\Models\Role', 'user_role', 'user_id', 'role_id');
    }

    /**
     * @param $roles
     * @return bool
     */
    public function hasAnyRole($roles)
    {
        if (is_array($roles)) {
            foreach ($roles as $role) {
                if ($this->hasRole($role)) {
                    return true;
                }
            }
        } else {
            if ($this->hasRole($roles)) {
                return true;
            }
        }

        return false;
    }

    /**
     * @param $role
     * @return bool
     */
    public function hasRole($role)
    {
        if ($this->roles()->where('name', $role)->first()) {
            return true;
        } else {
            return false;
        }
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    const USERS_PER_PAGE = 5;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(self::USERS_PER_PAGE);

        return view('admin.users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);

        return view('admin.users.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $user = User::find($id);
        $result = $user->update(['name' => $data['name'], 'email' => $data['email']]);

        if ($result) {
            return redirect()->route('admin.user.index')->with('flash_message_success', 'User info was updated.');
        } else {
            return redirect()->route('admin.user.index')->with('flash_message_success', 'User info was not updated. Some error occurred.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);

        if ($user->delete()) {
            return redirect()->back()->with('flash_message_success', 'User was deleted.');
        } else {
            return redirect()->back()->with('flash_message_error', 'User was not deleted. Some error occurred.');
        }
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function postAdminAssignRoles(Request $request)
    {
        $user = User::where('email', $request['email'])->first();

        if (isset($request['role_user'])) {
            $user->roles()->attach(Role::where('name', 'User')->first());
        } else {
            $user->roles()->detach(Role::where('name', 'User')->first());
        }
        if (isset($request['role_author'])) {
            $user->roles()->attach(Role::where('name', 'Author')->first());
        } else {
            $user->roles()->detach(Role::where('name', 'Author')->first());
        }
        if (isset($request['role_admin'])) {
            $user->roles()->attach(Role::where('name', 'Admin')->first());
        } else {
            $user->roles()->detach(Role::where('name', 'Admin')->first());
        }

        return redirect()->back()->with('flash_message_success', 'Roles were successfully updated');
    }
}

app/Http/Controllers/User/ArticleController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Article;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    public function article($slug)
    {
        $article = Article::where('slug', $slug)->first();

        if(!isset($_COOKIE[$slug])){ // for vew count
            setcookie($slug, true, time()+60*60*24*30);
            $article->viewed += 1;
            $article->timestamps = false;
            $article->save();
        }

        $created_by = User::find($article->created_by)->name;

        return view('user.blog.article', [
            'article' => $article,
            'created_by' => $created_by,
        ]);
    }
}

app/Http/Controllers/User/CategoryController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * @param $slug
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function category($slug)
    {
        $category = Category::where('slug', $slug)->first();

        return view('user.blog.category', [
            'category' => $category,
            'articles' => $category->articles()->where('published', 1)->paginate(10)
        ]);
    }
}

app/Http/Controllers/User/SearchController.php
<?php
/**
 * Created by PhpStorm.
 * User: komp33beck
 * Date: 28.08.2018
 * Time: 13:57
 */

namespace App\Http\Controllers\User;


use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\User;
use Illuminate\Http\Request;

class SearchController extends Controller
{

    /**
     * Search articles
     *
     * @param  Request $request
     * @return mixed
     */
    public function search(Request $request)
    {

        if($request->has('q')) {

            $articles = Article::with(['categories'])->where('title', 'LIKE', '%'.$request->get('q').'%')->where('published', 1)->paginate(10);
            if($articles->count()){
                foreach($articles as $article){
                    $article->author = User::find($article->created_by)->name;
                }
                return view('user.blog.search',[
                    'articles' => $articles,
                    'q' => $request->get('q')
                ]);
            }
        }

        return view('user.blog.search',['q' => $request->get('q'), 'error' => 'No results found, please try with different keywords.']);

    }

}

resources/views/admin/users/edit.blade.php
@extends('layouts.adminLayout.admin_design')

@section('meta_title', 'Edit User')

@section('title', 'Edit User')

@section('content')

    @component('admin.components.breadcrumbs')
        @slot('title') User edit @endslot
        @slot('parent') Homepage @endslot
        @slot('active') User edit @endslot
    @endcomponent

    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 mx-auto">
                <form class="form-horizontal" action="{{ route('admin.user.update', $user) }}" method="post">
                    <input type="hidden" name="_method" value="put">
                    {{ csrf_field() }}
                    @include('admin.users.partials.form')

                    <input type="hidden" name="modified_by" value="{{Auth::id()}}">
                </form>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.adminLayout.admin_design')

@section('meta_title', 'Users')

@section('head_css')
    <link href="{{ asset('assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/extra-libs/multicheck/multicheck.css') }}" rel="stylesheet">
@endsection

@section('title', 'Users')

@section('content')
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">

        <div class="row">
            <div class="col-12 mx-auto">
                <div class="card">
                    @if(session('flash_message_error'))
                        <div class="alert alert-danger alert-block">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {!! session('flash_message_error') !!}
                        </div>
                    @endif
                    @if(session('flash_message_success'))
                        <div class="alert alert-success alert-block">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {!! session('flash_message_success') !!}
                        </div>
                    @endif
                    <div class="card-body">
                        <h5 class="card-title m-b-0">Users</h5>
                    </div>
                    <div>
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">updated_at</th>
                                <th scope="col">created_at</th>
                                <th scope="col">Roles</th>
                                <th scope="col">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->updated_at }}</td>
                                    <td>{{ $user->created_at }}</td>
                                    <td>
                                    <form action="{{ route('admin.assign') }}" method="post">
                                        User <input type="checkbox" {{ $user->hasRole('User') ? 'checked' : '' }} name="role_user">
                                        Author <input type="checkbox" {{ $user->hasRole('Author') ? 'checked' : '' }} name="role_author">
                                        Admin <input type="checkbox" {{ $user->hasRole('Admin') ? 'checked' : '' }} name="role_admin">

                                        {{ csrf_field() }}
                                        <input type="hidden" value="{{ $user->email }}" name="email">
                                        <button type="submit">Assign Roles</button>
                                    </form>
                                    <td  class="text-left">
                                        <form onsubmit="if(confirm('Delete?')){ return true }else{ return false }" action="{{route('admin.user.destroy', $user)}}" method="post">
                                            <a href="{{ route('admin.user.edit', $user->id) }}" class="btn"><i class="fa fa-edit"></i></a>
                                            <input type="hidden" name="_method" value="DELETE">
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-sm"><i class="fas fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        {{ $users->links() }}

    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->

@endsection

@section('bottom_js')
    <script src="{{ asset('assets/libs/flot.tooltip/js/jquery.flot.tooltip.min.js') }}"></script>
    <script src="{{ asset('assets/extra-libs/multicheck/datatable-checkbox-init.js') }}"></script>
    <script src="{{ asset('assets/extra-libs/multicheck/jquery.multicheck.js') }}"></script>
    <script src="{{ asset('assets/extra-libs/DataTables/datatables.min.js') }}"></script>
@endsection