routes/web.php
<?php
Route::match(['get', 'post'], '/login', 'Admin\AuthController@login')->name('login');
Route::match(['get', 'post'], '/register', 'Admin\AuthController@register')->name('register');

Route::group(['prefix' => 'admin', 'middleware' => 'roles', 'roles' => ['Admin', 'Author', 'User']], function () {
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::get('settings', 'Admin\SettingsController@settings')->name('admin.settings');
    Route::post('settings-post', 'Admin\SettingsController@postChangePassword')->name('admin.settings.post');

    Route::get('blog/category/{slug?}', 'User\CategoryController@category')->name('category');
    Route::get('blog/article/{slug?}', 'User\ArticleController@article')->name('article');

    Route::get('blog/search', 'User\SearchController@search')->name('admin.search');
});

Route::group(['prefix' => 'admin', 'middleware' => 'roles', 'roles' => ['Admin', 'Author']], function () {
    Route::resource('category', 'Admin\CategoryController', ['as' => 'admin']);
    Route::resource('article', 'Admin\ArticleController', ['as' => 'admin']);
});

Route::group(['prefix' => 'admin', 'middleware' => 'roles', 'roles' => ['Admin']], function () {
    Route::resource('user', 'Admin\UserController', ['as' => 'admin']);

    Route::post('users/update-roles', 'Admin\UserController@postAdminAssignRoles')->name('admin.assign');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('logout', 'Admin\AuthController@logout')->name('logout');
    Route::get('/', function () {
        return view('welcome');
    });
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Article extends Model
{
    /**
     * @var array
     */
    protected $fillable = ['title', 'slug', 'description_short', 'description', 'image', 'image_show', 'meta_title',
        'meta_description', 'meta_keyword', 'published', 'created_by', 'modified_by'];

    /**
     * Mutators
     *
     * @param $value
     */
    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = Str::slug(mb_substr($this->title, 0, 40) . "-" . \Carbon\Carbon::now()->format('dmHi'), '-');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function categories()
    {
        return $this->morphToMany('App\Models\Category', 'categoryable');
    }

    /**
     * @param $query
     * @param $count
     * @return mixed
     */
    public function scopeLastArticles($query, $count)
    {
        return $query->orderBy('created_at', 'desc')->take($count)->get();
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Repositories\ArticleRepository;
use App\Repositories\CategoryRepository;
use App\Models\Article;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    /**
     * space that we can use the repository from
     *
     * App\Models\Article
     */
    protected $articleRepository;
    /**
     * @var CategoryRepository
     */
    protected $categoryRepository;

    /**
     * ArticleController constructor.
     * @param ArticleRepository $articleRepository
     * @param CategoryRepository $categoryRepository
     * @param Article $articleModel
     * @param Category $categoryModel
     */
    public function __construct(ArticleRepository $articleRepository, CategoryRepository $categoryRepository)
    {
        $this->articleRepository = $articleRepository;
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.articles.index', [
            'articles' => $this->articleRepository->getPaginatedOrderBy(10, 'created_at', true)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.articles.create', [
            'article' => [],
            'categories' => $this->categoryRepository->getAll(),
            'delimiter' => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'published' => 'required',
            'title' => 'required',
            'description' => 'required',
        ]);

        $this->articleRepository->create($request->all());

        return redirect()->route('admin.article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('admin.articles.edit', [
            'article' => $article,
            'categories' => $this->articleRepository->getWhereWith(['children']),
            'delimiter' => '',
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $this->validate($request, [
            'published' => 'required',
            'title' => 'required',
            'description' => 'required',
        ]);

        $this->articleRepository->update($request->except('slug'), $article->id);

        return redirect()->route('admin.article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Article $article
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Article $article)
    {
        $this->articleRepository->delete($article->id);

        return redirect()->route('admin.article.index');
    }
}

app/Http/Controllers/User/ArticleController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Article;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    public function article($slug)
    {
        $article = Article::where('slug', $slug)->first();

        if(!isset($_COOKIE[$slug])){ // for vew count
            setcookie($slug, true, time()+60*60*24*30);
            $article->viewed += 1;
            $article->timestamps = false;
            $article->save();
        }

        $created_by = User::find($article->created_by)->name;

        return view('user.blog.article', [
            'article' => $article,
            'created_by' => $created_by,
        ]);
    }
}

resources/views/admin/articles/create.blade.php
@extends('layouts.adminLayout.admin_design')

@section('meta_title', 'Create Article')

@section('title', 'Create Article')

@section('content')

    @component('admin.components.breadcrumbs')
        @slot('title') Article create @endslot
        @slot('parent') Homepage @endslot
        @slot('active') Article create @endslot
    @endcomponent

    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 mx-auto">
                <form class="form-horizontal" action="{{ route('admin.article.store') }}" method="post">
                    {{ csrf_field() }}
                    @include('admin.articles.partials.form')

                    <input type="hidden" name="created_by" value="{{Auth::id()}}">
                </form>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/articles/edit.blade.php
@extends('layouts.adminLayout.admin_design')

@section('meta_title', 'Edit Article')

@section('title', 'Edit Article')

@section('content')

    @component('admin.components.breadcrumbs')
        @slot('title') Article edit @endslot
        @slot('parent') Homepage @endslot
        @slot('active') Article edit @endslot
    @endcomponent

    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 mx-auto">
                <form class="form-horizontal" action="{{ route('admin.article.update', $article) }}" method="post">
                    <input type="hidden" name="_method" value="put">
                    {{ csrf_field() }}
                    @include('admin.articles.partials.form')

                    <input type="hidden" name="modified_by" value="{{Auth::id()}}">
                </form>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.adminLayout.admin_design')

@section('meta_title', 'Articles')

@section('title', 'Articles')

@section('content')

    @component('admin.components.breadcrumbs')
        @slot('title') Articles list @endslot
        @slot('parent') Homepage @endslot
        @slot('active') Articles @endslot
    @endcomponent
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 mx-auto">
                <a href="{{ route('admin.article.create') }}" class="btn btn-primary pull-right">
                    <i class="fas fa-plus"></i> Create article</a>
                <table class="table table-striped">
                    <thead>
                    <th>Name</th>
                    <th>Publishing</th>
                    <th class="text-right">Actions</th>
                    </thead>
                    <tbody>
                    @forelse($articles as $article)
                        <tr>
                            <td>{{ $article->title  }}</td>
                            <td>{{ $article->published  }}</td>
                            <td class="text-right">
                                <form onsubmit="if(confirm('Delete?')){ return true }else{ return false }" action="{{route('admin.article.destroy', $article)}}" method="post">
                                    <input type="hidden" name="_method" value="DELETE">
                                    {{ csrf_field() }}

                                    <a class="btn" href="{{ route('admin.article.edit', $article) }}">
                                        <i class="fa fa-edit"></i></a>

                                    <button type="submit" class="btn"><i class="fas fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3" class="text-center"><h2>Data not found</h2></td>
                        </tr>
                    @endforelse
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="3">
                            <ul class="pagination pull-right">
                                {{ $articles->links() }}
                            </ul>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>


@endsection