routes/web.php
<?php
Route::match(['get', 'post'], '/login', 'Admin\AuthController@login')->name('login');
Route::match(['get', 'post'], '/register', 'Admin\AuthController@register')->name('register');

Route::group(['prefix' => 'admin', 'middleware' => 'roles', 'roles' => ['Admin', 'Author', 'User']], function () {
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::get('settings', 'Admin\SettingsController@settings')->name('admin.settings');
    Route::post('settings-post', 'Admin\SettingsController@postChangePassword')->name('admin.settings.post');

    Route::get('blog/category/{slug?}', 'User\CategoryController@category')->name('category');
    Route::get('blog/article/{slug?}', 'User\ArticleController@article')->name('article');

    Route::get('blog/search', 'User\SearchController@search')->name('admin.search');
});

Route::group(['prefix' => 'admin', 'middleware' => 'roles', 'roles' => ['Admin', 'Author']], function () {
    Route::resource('category', 'Admin\CategoryController', ['as' => 'admin']);
    Route::resource('article', 'Admin\ArticleController', ['as' => 'admin']);
});

Route::group(['prefix' => 'admin', 'middleware' => 'roles', 'roles' => ['Admin']], function () {
    Route::resource('user', 'Admin\UserController', ['as' => 'admin']);

    Route::post('users/update-roles', 'Admin\UserController@postAdminAssignRoles')->name('admin.assign');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('logout', 'Admin\AuthController@logout')->name('logout');
    Route::get('/', function () {
        return view('welcome');
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * Class Category
 * @package App\Models
 */
class Category extends Model
{
    /**
     * Mass assigned
     *
     * @var array
     */
    protected $fillable = ['title', 'slug', 'parent_id', 'published', 'created_by', 'modified_by'];

    /**
     * Mutators
     *
     * @param $value
     */
    public function setSlugAttribute($value) {
        $this->attributes['slug'] = Str::slug(mb_substr($this->title, 0, 40) . "-" . \Carbon\Carbon::now()->format('dmHi'), '-');
    }

    /**
     * Get children category
     */
    public function children()
    {
        return  $this->hasMany(self::class, 'parent_id');
    }

    /**
     * Polymorphic relation with articles
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function articles()
    {
        return $this->morphedByMany('App\Models\Article', 'categoryable');
    }

    /**
     * @param $query
     * @param $count
     * @return mixed
     */
    public function scopeLastCategories($query, $count)
    {
        return $query->orderBy('created_at', 'desc')->take($count)->get();
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use \App\Models\Category;
use App\Repositories\CategoryRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class CategoryController extends Controller
{
    /**
     * @var CategoryRepository
     */
    protected $categoryRepository;

    public function __construct(CategoryRepository $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->categoryRepository->getPaginatedOrderBy(10, 'created_at', true);

        return view('admin.categories.index', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create', [
            'category' => [],
            'categories' => $this->categoryRepository->getWhereWith(['children'], ['parent_id', '=', 0]),
            'delimiter' => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->categoryRepository->create($request->all());

        return redirect()->route('admin.category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', [
            'category' => $category,
            'categories' => $this->categoryRepository->getWhereWith(['children'], ['parent_id', '=', 0]),
            'delimiter' => '',
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->categoryRepository->update($request->except('slug'), $category->id);

        return redirect()->route('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Category $category)
    {
        $this->categoryRepository->delete($category->id);

        return redirect()->route('admin.category.index');
    }
}

app/Http/Controllers/User/CategoryController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * @param $slug
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function category($slug)
    {
        $category = Category::where('slug', $slug)->first();

        return view('user.blog.category', [
            'category' => $category,
            'articles' => $category->articles()->where('published', 1)->paginate(10)
        ]);
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.adminLayout.admin_design')

@section('meta_title', 'Create Category')

@section('title', 'Create Category')

@section('content')

    @component('admin.components.breadcrumbs')
        @slot('title') Category create @endslot
        @slot('parent') Homepage @endslot
        @slot('active') Category create @endslot
    @endcomponent

    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 mx-auto">
                <form class="form-horizontal" action="{{ route('admin.category.store') }}" method="post">
                    {{ csrf_field() }}
                    @include('admin.categories.partials.form')
                </form>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.adminLayout.admin_design')

@section('meta_title', 'Create Category')

@section('title', 'Create Category')

@section('content')

    @component('admin.components.breadcrumbs')
        @slot('title') Category editing @endslot
        @slot('parent') Homepage @endslot
        @slot('active') Category create @endslot
    @endcomponent

    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 mx-auto">
                <form class="form-horizontal" action="{{ route('admin.category.update', $category) }}" method="post">
                    <input type="hidden" name="_method" value="put">
                    {{ csrf_field() }}
                    @include('admin.categories.partials.form')
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.adminLayout.admin_design')

@section('meta_title', 'Categories')

@section('title', 'Categories')

@section('content')

    @component('admin.components.breadcrumbs')
        @slot('title') Categories list @endslot
        @slot('parent') Homepage @endslot
        @slot('active') Categories @endslot
    @endcomponent
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 mx-auto">
                <a href="{{ route('admin.category.create') }}" class="btn btn-primary pull-right">
                    <i class="fas fa-plus"></i> Create category</a>
                <table class="table table-striped">
                    <thead>
                    <th>Name</th>
                    <th>Publishing</th>
                    <th class="text-right">Actions</th>
                    </thead>
                    <tbody>
                    @forelse($categories as $category)
                        <tr>
                            <td>{{ $category->title  }}</td>
                            <td>{{ $category->published  }}</td>
                            <td class="text-right">
                                <form onsubmit="if(confirm('Delete?')){ return true }else{ return false }" action="{{route('admin.category.destroy', $category)}}" method="post">
                                    <input type="hidden" name="_method" value="DELETE">
                                    {{ csrf_field() }}

                                    <a class="btn" href="{{ route('admin.category.edit', $category) }}">
                                        <i class="fa fa-edit"></i></a>

                                    <button type="submit" class="btn"><i class="fas fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3" class="text-center"><h2>Data not found</h2></td>
                        </tr>
                    @endforelse
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="3">
                            <ul class="pagination pull-right">
                                {{ $categories->links() }}
                            </ul>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>


@endsection